---
image: newcity/builder:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GITHUB_UPSTREAM_PRIVATE_KEY")
    - make init
    - make install
    - make clone
    - make replay
  artifacts:
    paths:
      - build

test:
  stage: test
  image: newcity/lamp-testing-drupal
  script:
    - cd /
    - mv $CI_PROJECT_DIR/build/* /app/
    - ./startup.sh
    - cd $CI_PROJECT_DIR/test
    - mkdir data
    - npm install
    - cd scripts
    - ava login.js
    - ava create-nodes.js
  
push:master:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GITHUB_UPSTREAM_PRIVATE_KEY")
    - make init
    - make push
  only:
    - master
