---
image: newcity/builder:latest

variables:
  REMOTE_REPO: "git@github.com:ahebrank/test-upstream.git"
  BUILD_REPO: "/tmp/upstream"
  
before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$GITHUB_PRIVATE_KEY")
  - make .ci_init

stages:
  - build
  - push

build:
  script:
    - composer build-assets
  only:
    - master

push:
  script:
    - export COMMIT_MESSAGE="$( echo git log -1 --pretty=%B | cat | tr -d \"\'\" )"
    - git clone $(REMOTE_REPO) $(BUILD_REPO)
    - rsync -av . $(BUILD_REPO)/
    - cd $(BUILD_REPO) && git add . && git commit -m "BUILD: $(COMMIT_MESSAGE)" && git push origin master
