---
image: newcity/builder:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GITLAB_BUILD_KEY")
    - make install
    - make clone
    - make replay
  artifacts:
    paths:
      - build

test:
  stage: test
  image: newcity/lamp-testing-drupal
  script:
    - rm -rf /app/*
    - mv $CI_PROJECT_DIR/build/* /app/
    - /startup.sh
    - cd /test
    - mkdir data
    - mv $CI_PROJECT_DIR/test-scripts scripts
    - cd scripts
    - ava login.js
    # - ava create-nodes.js
  
push:master:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GITLAB_BUILD_KEY")
    - make push
  only:
    - master
