---
image: newcity/builder:latest

before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$GITHUB_UPSTREAM_PRIVATE_KEY")
  - make init

push:master:
  script:
    - make install
    - make clone
    - make replay
  only:
    - master
