---
image: newcity/builder:latest

before_script:
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$GITHUB_PRIVATE_KEY")
  - make init

push:master:
  script:
    - make install
    - make clone
    - make replay
    - make push
  only:
    - master
